hostname = jdforrepam.com, moduokejt.com, hbstmg.com, cnrmwy.com
^http[s]?:\/\/(cnrmwy|jdforrepam|moduokejt|hbstmg)\.com\/api\/v1\/movies\/(.+)\/play url script-request-header https://cdn.jsdelivr.net/gh/ericgidseg/Other@main/javdba.js
^http[s]?:\/\/(cnrmwy|jdforrepam|moduokejt|hbstmg)\.com\/api\/v1\/movies\/(.+)\/play url response-body "success":\d+ response-body "success":1
#^http[s]?:\/\/(cnrmwy|jdforrepam|moduokejt|hbstmg)\.com\/api\/v1\/users url script-response-body https://cdn.jsdelivr.net/gh/ericgidseg/Other@main/javdbs.js
