hostname = 91mingyang.com, jsqcwd.com,ossse.com,mnter.com
# > JavDB解锁会员
^http[s]?:\/\/91mingyang|jsqcwd|ossse|mnter)\.com\/api\/v1\/movies\/(.+)\/play url script-request-header http://ox.xmkczs.com/quantumultX/javdba.js
^http[s]?:\/\/(91mingyang|jsqcwd|ossse|mnter)\.com\/api\/v1\/movies\/(.+)\/play url response-body "success":\d+ response-body "success":1
