hostname = 91mingyang.com, jsqcwd.com,ossse.com,mnter.com
# > JavDB解锁会员
^https?:\/\/(91mingyang|jsqcwd|ossse|mnter)\.com\/api\/v1\/movies\/.*\/play url script-request-header https://raw.githubusercontent.com/yqc007/QuantumultX/master/JavDBCrack.js
