hostname= yugedu.com,mnter.com
^http[s]?:\/\/(yugedu|mnter|yiliang8888)\.com\/api\/v1\/movies\/(.+)\/play url script-request-header http://ox.xmkczs.com/quantumultX/javdba.js
^http[s]?:\/\/(yugedu|mnter|yiliang8888)\.com\/api\/v1\/movies\/(.+)\/play url response-body "success":\d+ response-body "success":1
