hostname = *.miguvideo.com
# > 咪咕视频
# >> indexC
^https?:\/\/.*\.miguvideo\.com\/ability\/.+\/indexContract\? url script-response-body https://hub.nan.ge/Script/MiGu/indexC.js
# >> playURL
(^https?:\/\/play\.miguvideo\.com\/playurl\/v1\/play\/playurl|^https?:\/\/.*\.miguvideo\.com\/gateway\/playurl\/.+\/play\/?) url script-response-body https://hub.nan.ge/Script/MiGu/PlayUrl.js
# >> manage
^https?:\/\/app-sc\.miguvideo\.com\/app-management\/.+\/resolution\/? url script-response-body https://hub.nan.ge/Script/MiGu/Manage.js
# >> member
^https?:\/\/.*\.miguvideo\.com\/ability\/.+\/member-info\? url script-response-body https://hub.nan.ge/Script/MiGu/Member.js
