hostname = aiqicha.baidu.com, trade-acs.m.taobao.com, api.m.jd.com, shukego.com, moduokejt.com, *.gotokeep.com,

#WPS解锁  超级会员、wps会员、稻壳会员 (By eHpo)
^https://account.wps.*/api/users/ url script-response-body https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Wps.js
# 爱企查vip
;^https:\//aiqicha.baidu.com\/usercenter\/getvipinfoajax url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/aiqicha.js
# 京东比价
# 比价信息显示在商品下方
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig) url script-response-body https://raw.githubusercontent.com/zwf234/rules/master/js/jd_price.js
# 淘宝比价
# 历史价格在“保障”中显示，需要点击“保障”才能看到，和京东不一样
# “保障”显示在商品下方
# 如果还是不显示，那就把app卸载重新安装
^http:\/\/.+\/amdc\/mobileDispatch url script-request-body https://raw.githubusercontent.com/zwf234/rules/master/js/tb_price.js
^https?:\/\/trade-acs\.m\.taobao\.com\/gw\/mtop\.taobao\.detail\.getdetail url script-response-body https://raw.githubusercontent.com/zwf234/rules/master/js/tb_price.js
#JAV解锁VIP
^http[s]?:\/\/(shukego|moduokejt)\.com\/api\/v1\/movies\/(.+)\/play url script-request-header https://xmkczs.com/quantumultX/javdba.js
^http[s]?:\/\/(shukego|moduokejt)\.com\/api\/v1\/movies\/(.+)\/play url response-body "success":\d+ response-body "success":1
;^http[s]?:\/\/(shukego|moduokejt)\.com\/api\/v1\/users url script-response-body https://xmkczs.com/quantumultX/javdbs.js
# keep解锁会员
^https://(.+).gotokeep.com(/athena/v5/people/my|/nuocha/plans) url script-response-body https://raw.githubusercontent.com/nameking77/Qx/main/rewrite/keep
