hostname = aiqicha.baidu.com, tagit.hyhuo.com, trade-acs.m.taobao.com, api.m.jd.com, api.weibo.cn, mapi.weibo.com, *.uve.weibo.com, shukego.com, yugedu.com, *.gotokeep.com

#WPS解锁  超级会员、wps会员、稻壳会员 (By eHpo)
^https://account.wps.*/api/users/ url script-response-body https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Wps.js
# 爱企查vip
;^https:\//aiqicha.baidu.com\/usercenter\/getvipinfoajax url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/aiqicha.js
# > 拦截100解锁超级会员
^https?:\/\/tagit\.hyhuo\.com\/cypt\/block100\/get_vip_info$ url script-response-body https://raw.githubusercontent.com/yqc007/QuantumultX/master/Block100SVIPCrack.js
# 京东比价
# 比价信息显示在商品下方
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig) url script-response-body https://raw.githubusercontent.com/zwf234/rules/master/js/jd_price.js
# 淘宝比价
# 历史价格在“保障”中显示，需要点击“保障”才能看到，和京东不一样
# “保障”显示在商品下方
# 如果还是不显示，那就把app卸载重新安装
^http:\/\/.+\/amdc\/mobileDispatch url script-request-body https://raw.githubusercontent.com/zwf234/rules/master/js/tb_price.js
^https?:\/\/trade-acs\.m\.taobao\.com\/gw\/mtop\.taobao\.detail\.getdetail url script-response-body https://raw.githubusercontent.com/zwf234/rules/master/js/tb_price.js
#微博
^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua) url script-response-body https://raw.githubusercontent.com/yichahucha/surge/master/wb_launch.js
^https?://m?api\.weibo\.c(n|om)/2/(statuses/(unread|extend|positives/get|(friends|video)(/|_)(mix)?timeline)|stories/(video_stream|home_list)|(groups|fangle)/timeline|profile/statuses|comments/build_comments|photo/recommend_list|service/picfeed|searchall|cardlist|page|!/(photos/pic_recommend_status|live/media_homelist)|video/tiny_stream_video_list|photo/info|remind/unread_count) url script-response-body https://raw.githubusercontent.com/yichahucha/surge/master/wb_ad.js
#JAV解锁VIP
^http[s]?:\/\/(shukego|yugedu|hbstmg)\.com\/api\/v1\/movies\/(.+)\/play url script-request-header https://xmkczs.com/quantumultX/javdba.js
^http[s]?:\/\/(shukego|yugedu|hbstmg)\.com\/api\/v1\/movies\/(.+)\/play url response-body "success":\d+ response-body "success":1
;^http[s]?:\/\/(shukego|yugedu|hbstmg)\.com\/api\/v1\/users url script-response-body https://xmkczs.com/quantumultX/javdbs.js
# keep解锁会员
^https://(.+).gotokeep.com(/athena/v5/people/my|/nuocha/plans) url script-response-body https://raw.githubusercontent.com/nameking77/Qx/main/rewrite/keep
